version: "3.8"

networks:
    laravel:
        name: GeoCodeTest

services:

    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel
        depends_on:
            - php
            - mysql
            - redis

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel


    mysql:
        image: mysql:5.7.32
        container_name: mysql
        # restart: unless-stopped
        # tty: true
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laraveldb
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
        networks:
            - laravel


    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel

    artisan:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ["php", "artisan"]
        networks:
            - laravel

    npm:
        build:
            context: .
            dockerfile: npm.dockerfile
        container_name: npm
        volumes:
            - ./src:/var/www/html
        entrypoint: ["npm"]
        networks:
            - laravel







